network:
  ip: 192.168.2.221
  port: 8083
webui:
  host: 192.168.2.221
  port: 5003
log: INFO
proxy:
  read_buffer_size: 4096
db:
  delete_on_exit: false
performance:
  tcp_subflow_info_features: all
  measurement_interval_ms: 500
