network:
  ip: 192.168.2.221
  port: 8080
proxy:
  read_buffer_size: 4096
log:
  level: DEBUG
  output_to_console: 1
  path: /var/log/tc_server_py
  filename: .tc_server_py.log
performance:
  tcp_subflow_info_features:
    - tcpi_rtt
  measurement_interval_ms: 5
  output_file_path: /var/log/tc_server_py
  output_file_prefix: .performance_log

